# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_guide.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='route_guide.proto',
  package='wawcode_shame',
  syntax='proto3',
  serialized_pb=_b('\n\x11route_guide.proto\x12\rwawcode_shame\"\x1d\n\x0fGetEventRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x12\n\x10PutEventResponse\"$\n\x08Location\x12\x0b\n\x03Lat\x18\x01 \x01(\x01\x12\x0b\n\x03Lon\x18\x02 \x01(\x01\"V\n\x17\x45ventsInDistanceRequest\x12)\n\x08location\x18\x01 \x01(\x0b\x32\x17.wawcode_shame.Location\x12\x10\n\x08\x64istance\x18\x02 \x01(\x03\"\x92\x01\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x10\n\x08\x64istrict\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x0f\n\x07\x63reated\x18\x05 \x01(\x03\x12)\n\x08location\x18\x06 \x01(\x0b\x32\x17.wawcode_shame.Location\x12\x0c\n\x04type\x18\x07 \x01(\t\".\n\x06\x45vents\x12$\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x14.wawcode_shame.Event2\xac\x02\n\rEventsService\x12\x41\n\x08PutEvent\x12\x14.wawcode_shame.Event\x1a\x1f.wawcode_shame.PutEventResponse\x12\x43\n\tPutEvents\x12\x15.wawcode_shame.Events\x1a\x1f.wawcode_shame.PutEventResponse\x12Q\n\x10\x45ventsInDistance\x12&.wawcode_shame.EventsInDistanceRequest\x1a\x15.wawcode_shame.Events\x12@\n\x08GetEvent\x12\x1e.wawcode_shame.GetEventRequest\x1a\x14.wawcode_shame.Eventb\x06proto3')
)




_GETEVENTREQUEST = _descriptor.Descriptor(
  name='GetEventRequest',
  full_name='wawcode_shame.GetEventRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='wawcode_shame.GetEventRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=65,
)


_PUTEVENTRESPONSE = _descriptor.Descriptor(
  name='PutEventResponse',
  full_name='wawcode_shame.PutEventResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=85,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='wawcode_shame.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Lat', full_name='wawcode_shame.Location.Lat', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Lon', full_name='wawcode_shame.Location.Lon', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=123,
)


_EVENTSINDISTANCEREQUEST = _descriptor.Descriptor(
  name='EventsInDistanceRequest',
  full_name='wawcode_shame.EventsInDistanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='wawcode_shame.EventsInDistanceRequest.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='wawcode_shame.EventsInDistanceRequest.distance', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=211,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='wawcode_shame.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='wawcode_shame.Event.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category', full_name='wawcode_shame.Event.category', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='district', full_name='wawcode_shame.Event.district', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='wawcode_shame.Event.address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created', full_name='wawcode_shame.Event.created', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='wawcode_shame.Event.location', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='wawcode_shame.Event.type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=360,
)


_EVENTS = _descriptor.Descriptor(
  name='Events',
  full_name='wawcode_shame.Events',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='events', full_name='wawcode_shame.Events.events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=408,
)

_EVENTSINDISTANCEREQUEST.fields_by_name['location'].message_type = _LOCATION
_EVENT.fields_by_name['location'].message_type = _LOCATION
_EVENTS.fields_by_name['events'].message_type = _EVENT
DESCRIPTOR.message_types_by_name['GetEventRequest'] = _GETEVENTREQUEST
DESCRIPTOR.message_types_by_name['PutEventResponse'] = _PUTEVENTRESPONSE
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['EventsInDistanceRequest'] = _EVENTSINDISTANCEREQUEST
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Events'] = _EVENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetEventRequest = _reflection.GeneratedProtocolMessageType('GetEventRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETEVENTREQUEST,
  __module__ = 'route_guide_pb2'
  # @@protoc_insertion_point(class_scope:wawcode_shame.GetEventRequest)
  ))
_sym_db.RegisterMessage(GetEventRequest)

PutEventResponse = _reflection.GeneratedProtocolMessageType('PutEventResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUTEVENTRESPONSE,
  __module__ = 'route_guide_pb2'
  # @@protoc_insertion_point(class_scope:wawcode_shame.PutEventResponse)
  ))
_sym_db.RegisterMessage(PutEventResponse)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'route_guide_pb2'
  # @@protoc_insertion_point(class_scope:wawcode_shame.Location)
  ))
_sym_db.RegisterMessage(Location)

EventsInDistanceRequest = _reflection.GeneratedProtocolMessageType('EventsInDistanceRequest', (_message.Message,), dict(
  DESCRIPTOR = _EVENTSINDISTANCEREQUEST,
  __module__ = 'route_guide_pb2'
  # @@protoc_insertion_point(class_scope:wawcode_shame.EventsInDistanceRequest)
  ))
_sym_db.RegisterMessage(EventsInDistanceRequest)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'route_guide_pb2'
  # @@protoc_insertion_point(class_scope:wawcode_shame.Event)
  ))
_sym_db.RegisterMessage(Event)

Events = _reflection.GeneratedProtocolMessageType('Events', (_message.Message,), dict(
  DESCRIPTOR = _EVENTS,
  __module__ = 'route_guide_pb2'
  # @@protoc_insertion_point(class_scope:wawcode_shame.Events)
  ))
_sym_db.RegisterMessage(Events)



_EVENTSSERVICE = _descriptor.ServiceDescriptor(
  name='EventsService',
  full_name='wawcode_shame.EventsService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=411,
  serialized_end=711,
  methods=[
  _descriptor.MethodDescriptor(
    name='PutEvent',
    full_name='wawcode_shame.EventsService.PutEvent',
    index=0,
    containing_service=None,
    input_type=_EVENT,
    output_type=_PUTEVENTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PutEvents',
    full_name='wawcode_shame.EventsService.PutEvents',
    index=1,
    containing_service=None,
    input_type=_EVENTS,
    output_type=_PUTEVENTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EventsInDistance',
    full_name='wawcode_shame.EventsService.EventsInDistance',
    index=2,
    containing_service=None,
    input_type=_EVENTSINDISTANCEREQUEST,
    output_type=_EVENTS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetEvent',
    full_name='wawcode_shame.EventsService.GetEvent',
    index=3,
    containing_service=None,
    input_type=_GETEVENTREQUEST,
    output_type=_EVENT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENTSSERVICE)

DESCRIPTOR.services_by_name['EventsService'] = _EVENTSSERVICE

# @@protoc_insertion_point(module_scope)
